<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AI-Powered Paperwork Drafting | HomeDirect</title>
  <link rel="stylesheet" href="assets/css/styles.css" />
  <style>
    .paperwork-container {
      padding: 2rem 1rem;
      max-width: 900px;
      margin: 0 auto;
      font-family: 'Inter', sans-serif;
    }

    .paperwork-container h1 {
      font-size: 2rem;
      font-weight: 700;
      margin-bottom: 1rem;
    }

    .paperwork-container h2 {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 1rem;
    }

    .paperwork-container p {
      font-size: 1rem;
      line-height: 1.7;
      color: #374151;
      margin-bottom: 1.5rem;
    }

    .paperwork-container ul {
      list-style: disc;
      padding-left: 1.5rem;
      margin-bottom: 1.5rem;
      color: #374151;
    }

    .paperwork-container .disclaimer {
      color: #6b7280;
      margin-bottom: 2rem;
    }
  </style>
</head>
<body>

<?php include 'navbar.php'; ?>

<main class="paperwork-container">
  <h1>AI-Powered Property Paperwork Drafting</h1>

  <p>
    HomeDirect introduces a smarter way to handle your property documents. Whether you're selling or buying, our AI Assistant can help you generate a professional draft agreement based on your property listing. This includes sale agreements, custom clauses, property summaries, and more — all generated from the details you provide.
  </p>

  <h2>How to Use the AI Assistant</h2>
  <p>
    To get a property paperwork draft, simply open the AI Assistant (bottom-right chat icon) and ask it to create a sale agreement for your listing. Make sure to include:
  </p>
  <ul>
    <li>Your desired deposit percentage (e.g., "add 20% deposit clause")</li>
    <li>The expected completion date (e.g., "completion date is 2025-12-01")</li>
    <li>Any specific conditions you want added (e.g., "include buyer solicitor clause" or "add penalty for late payment")</li>
  </ul>

  <h2>What the AI Generates</h2>
  <ul>
    <li>Initial sale or lease agreement drafts</li>
    <li>Property summaries and legal clauses</li>
    <li>Custom terms you provide in the chat</li>
    <li>Final output delivered as a downloadable PDF</li>
  </ul>

  <h2>Important Disclaimer</h2>
  <p class="disclaimer">
    All paperwork generated by AI is for informational purposes only and should not be used without professional legal review. HomeDirect is not a law firm and does not offer legal advice. <strong>Always consult a solicitor before using any AI-generated legal document.</strong>
  </p>

  <p>
    Let AI handle the draft — and let your solicitor finalize it with confidence.
  </p>
</main>

<?php include 'footer.php'; ?>

</body>
</html>
